const videos = [
    {
        id: 1,
        src: require('~/videos/video1.mp4'),
        author: 'legiang',
        desc: 'Một ngày đẹp trời bên cạnh những người bạn thân thiết.',
        music: 'Nhạc nền - hongloan19930',
        likes: 500,
        hearts: 150,  // Số lượt thả tim
        comments: 20,
        shares: 30,
        avatar: 'https://example.com/avatar1.jpg',
    },
    {
        id: 2,
        src: require('~/videos/video2.mp4'),
        author: 'thanhquan',
        desc: 'Khám phá vẻ đẹp của thiên nhiên trong từng khung hình.',
        music: 'Nhạc nền - nhacxua',
        likes: 620,
        hearts: 180,
        comments: 35,
        shares: 25,
        avatar: 'https://example.com/avatar2.jpg',
    },
    {
        id: 3,
        src: require('~/videos/video3.mp4'),
        author: 'giangdethuong',
        desc: 'Những khoảnh khắc tuyệt vời bên gia đình.',
        music: 'Nhạc nền - yeuthuong',
        likes: 320,
        hearts: 90,
        comments: 12,
        shares: 15,
        avatar: 'https://example.com/avatar3.jpg',
    },
    {
        id: 4,
        src: require('~/videos/video4.mp4'),
        author: 'giangxinhdep',
        desc: 'Bước nhảy tuyệt đẹp của những vũ công chuyên nghiệp.',
        music: 'Nhạc nền - dapchunhieu',
        likes: 400,
        hearts: 120,
        comments: 18,
        shares: 22,
        avatar: 'https://example.com/avatar4.jpg',
    },
    {
        id: 5,
        src: require('~/videos/video5.mp4'),
        author: 'giangvuto',
        desc: 'Chia sẻ những bí quyết nấu ăn đơn giản và ngon.',
        music: 'Nhạc nền - amthuc',
        likes: 700,
        hearts: 300,
        comments: 50,
        shares: 40,
        avatar: 'https://example.com/avatar5.jpg',
    },
    {
        id: 6,
        src: require('~/videos/video6.mp4'),
        author: 'giangkute',
        desc: 'Đi dạo trên bãi biển trong ánh hoàng hôn.',
        music: 'Nhạc nền - thiennhien',
        likes: 450,
        hearts: 200,
        comments: 30,
        shares: 28,
        avatar: 'https://example.com/avatar6.jpg',
    },
    {
        id: 7,
        src: require('~/videos/video7.mp4'),
        author: 'giangngucto',
        desc: 'Chuyến phiêu lưu khám phá các địa điểm thú vị.',
        music: 'Nhạc nền - phieuluu',
        likes: 550,
        hearts: 250,
        comments: 40,
        shares: 35,
        avatar: 'https://example.com/avatar7.jpg',
    },
    {
        id: 8,
        src: require('~/videos/video8.mp4'),
        author: 'nguyendinh',
        desc: 'Những câu chuyện thú vị từ cuộc sống hàng ngày.',
        music: 'Nhạc nền - cuocsong',
        likes: 310,
        hearts: 80,
        comments: 10,
        shares: 20,
        avatar: 'https://example.com/avatar8.jpg',
    },
    {
        id: 9,
        src: require('~/videos/video9.mp4'),
        author: 'minhha',
        desc: 'Hành trình đi bộ đường dài và ngắm nhìn cảnh đẹp.',
        music: 'Nhạc nền - duongda',
        likes: 520,
        hearts: 175,
        comments: 25,
        shares: 32,
        avatar: 'https://example.com/avatar9.jpg',
    },
    {
        id: 10,
        src: require('~/videos/video10.mp4'),
        author: 'tuananh',
        desc: 'Chia sẻ các mẹo trang trí nhà cửa độc đáo.',
        music: 'Nhạc nền - trangtri',
        likes: 660,
        hearts: 220,
        comments: 28,
        shares: 45,
        avatar: 'https://example.com/avatar10.jpg',
    },
];
export default videos;