const routes = {
    home: '/',
    following: '/following',
    profile: '/@:nickname',
    search: '/search',
    upload: '/tiktokstudio/upload',
    homeUpload: '/tiktokstudio',
    post: '/tiktokstudio/content',
    comment: '/tiktokstudio/comment',
    analytics: '/tiktokstudio/analytics',
    inspirations: '/tiktokstudio/inspiration',
    unlimitedsounds: '/tiktokstudio/sound-library',
    uploadVideo:'/tiktokstudio/upload/video',
    create: 'https://www.tiktok.com/creator-academy/',
    feedback: '/tiktokstudio/feedback',
    live: '/live',
    messages: '/messages',
    explore: '/explore',
    friend: '/friend',
};
export default routes;
